<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);

// Set image
$headerImage = '';
if ($module == 'contact') {
    $headerImage = 'https://www.faza.ir/upload/images/header-contactus.jpg';
} elseif ($module == 'shop') {
    $headerImage = 'https://www.faza.ir/upload/images/header-procurement.jpg';
} elseif ($module == 'page') {
    $d = (array) Pi::service('url')->getRouteMatch();
    foreach ($d as $value) {
        $a[] = $value;
    }
    if ($a[1]['action'] == 'consult') {
        $headerImage = 'https://www.faza.ir/upload/images/header-consult.jpg';
    }
    if ($a[1]['action'] == 'education') {
        $headerImage = 'https://www.faza.ir/upload/images/header-education.jpg';
    }
    if ($a[1]['action'] == 'nano-food') {
        $headerImage = 'https://www.faza.ir/upload/images/header-nano-food.jpg';
    }
}

?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<!-- Header: brand, slogan, user bar -->
<?php if ($module == 'system') { ?>
    <header class="pi-header">
        <div class="pi-header-body">
            <div class="pi-header-user">
                <nav class="navbar navbar-default">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="navbar-header">
                                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                    <?php if ($module == 'system') { ?>
                                        <h1>
                                            <a href="<?php echo Pi::url($this->url('home')); ?>/" title="<?php echo _escape($sitename); ?>">
                                                <?php echo _escape($sitename); ?>
                                            </a>
                                        </h1>
                                    <?php } else { ?>
                                        <h2>
                                            <a href="<?php echo Pi::url($this->url('home')); ?>/" title="<?php echo _escape($sitename); ?>">
                                                <?php echo _escape($sitename); ?>
                                            </a>
                                        </h2>
                                    <?php } ?>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                                    <div class="navbar-right">
                                        <?php echo $this->widget('system-user-bar'); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <div class="pi-header-box  clearfix">
            <div class="col-md-offset-3 col-md-6">
                <div class="pi-header-box-text">
                    <p>به وب سایت فضا خوش آمدید</p>
                </div>
                <?php echo $this->widget('search-search'); ?>
            </div>
        </div>
            <picture>
                <!--[if IE 9]><video style="display: none;"><![endif]-->
                <source data-srcset="<?php echo $this->assetTheme('image/header-mobi-ete.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/header-mobi-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-smart-ete.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/header-smart-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-tab-ete.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/header-tab-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-lap-ete.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/header-lap-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-desk-ete.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/header-desk-ete.jpg'); ?>">
                <!--[if IE 9]></video><![endif]-->
                <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>">
            </picture>
    </header>
    <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
    <section class="pi-section  clearfix <?php if ($module != 'system') { echo 'pi-section-page';} ?>">
        <?php if ($breadcrumbs) { ?>
            <div class="pi-breadcrumbs">
                <div class="container">
                    <div class="row">
                        <?php echo $breadcrumbs; ?>
                    </div>
                </div>
            </div>
        <?php } ?>
        <div class="container">
            <div class="pi-main-container">
                <!-- Flash messenger -->
                <?php include $this->template('flash-messenger'); ?>
                <div class="row">
                    <!-- Left zone -->
                    <?php if (!empty($blocks['1'])) { ?>
                        <div class="pi-zone-1 col-md-4">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <div class="<?php
                    if (isset($blocks['1']) && isset($blocks['8'])) {
                        echo 'col-md-4';
                    } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                        echo 'col-md-8';
                    } else {
                        echo 'col-md-12';
                    }
                    ?>">
                        <!-- Center top zone -->
                        <?php if (isset($blocks['2'])) { ?>
                            <div class="pi-zone-2">
                                <?php foreach ($blocks['2'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-3">
                                    <?php
                                    if (isset($blocks['3'])) {
                                        foreach ($blocks['3'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-4">
                                    <?php
                                    if (isset($blocks['4'])) {
                                        foreach ($blocks['4'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Module content starts -->
                        <?php if (!empty($content)) { ?>
                            <div class="<?php echo $module; ?>">
                                <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                    <?php echo $content; ?>
                                </div>
                                <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Right zone -->
                    <?php if (isset($blocks['8'])) { ?>
                        <div class="col-md-4 pi-zone-8">
                            <?php foreach ($blocks['8'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="pi-section-center-image">
            <div class="pi-section-center-image-desc">
                <div class="pi-section-center-image-box">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-offset-2 col-md-8">
                                <div class="text-center">
                                    <div class="pi-section-center-image-desc-text">در باشگاه نخبگان فضایی</div>
                                    <div class="pi-section-center-image-desc-btn"><a title="ثبت نام کنید" href="<?php echo Pi::url($this->url('home')); ?>/user/register" class="btn btn-primary btn-lg">ثبت نام کنید</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <picture>
                <!--[if IE 9]><video style="display: none;"><![endif]-->
                <source data-srcset="<?php echo $this->assetTheme('image/section-center-mobi-ete.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/section-center-mobi-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/section-center-smart-ete.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/section-center-smart-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/section-center-tab-ete.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/section-center-tab-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/section-center-lap-ete.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/section-center-lap-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/section-center-xlap-ete.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/section-center-xlap-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/section-center-desk-ete.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/section-center-desk-ete.jpg'); ?>">
                <!--[if IE 9]></video><![endif]-->
                <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/section-center-xlap-ete.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/section-center-xlap-ete.jpg'); ?>">
            </picture>
            </header>
        </div>
        <div class="container">
            <div class="pi-main-container">
                <!-- Module content ends -->
                <div class="row">
                    <?php if (isset($blocks['5'])) { ?>
                        <div class="col-md-12 pi-zone-5">
                            <?php foreach ($blocks['5'] as $block) {
                                    include $blockTemplate;
                                } ?>
                        </div>
                      <?php } ?>
                    <?php if (isset($blocks['6'])) { ?>
                        <div class="col-md-12 pi-zone-6">
                            <?php foreach ($blocks['6'] as $block) {
                                    include $blockTemplate;
                                } ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </section>
    <!-- Bottom foot zone -->
    <?php if (isset($blocks['7'])) { ?>
        <section class="pi-section-news">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 pi-zone-7">
                        <?php foreach ($blocks['7'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                </div>
            </div>
        </section>
    <?php } ?>
    <?php if (isset($blocks['99'])) { ?>
        <section class="pi-section-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                </div>
            </div>
        </section>
    <?php } ?>
<?php } else { ?>
    <header class="pi-header">
        <div class="pi-header-body">
            <div class="pi-header-user">
                <nav class="navbar navbar-default">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="navbar-header">
                                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                    <?php if ($module == 'system') { ?>
                                        <h1>
                                            <a href="<?php echo Pi::url($this->url('home')); ?>/" title="<?php echo _escape($sitename); ?>">
                                                <?php echo _escape($sitename); ?>
                                            </a>
                                        </h1>
                                    <?php } else { ?>
                                        <h2>
                                            <a href="<?php echo Pi::url($this->url('home')); ?>/" title="<?php echo _escape($sitename); ?>">
                                                <?php echo _escape($sitename); ?>
                                            </a>
                                        </h2>
                                    <?php } ?>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                                    <div class="navbar-right">
                                        <?php echo $this->widget('system-user-bar'); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <?php if (empty($headerImage)) { ?>
            <div class="pi-header-box  clearfix">
                <div class="col-md-offset-3 col-md-6">
                    <div class="pi-header-box-text">
                        <p>به وب سایت فضا خوش آمدید</p>
                    </div>
                    <?php echo $this->widget('search-search'); ?>
                </div>
            </div>
            <picture>
                <!--[if IE 9]><video style="display: none;"><![endif]-->
                <source data-srcset="<?php echo $this->assetTheme('image/header-mobi-ete.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/header-mobi-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-smart-ete.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/header-smart-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-tab-ete.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/header-tab-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-lap-ete.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/header-lap-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>">
                <source data-srcset="<?php echo $this->assetTheme('image/header-desk-ete.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/header-desk-ete.jpg'); ?>">
                <!--[if IE 9]></video><![endif]-->
                <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>">
            </picture>
        <?php } else { ?>
            <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $headerImage; ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $headerImage; ?>">
        <?php } ?>
    </header>
    <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
    <section class="pi-section  clearfix <?php if ($module != 'system') { echo 'pi-section-page';} ?>">
        <?php if ($breadcrumbs) { ?>
            <div class="pi-breadcrumbs">
                <div class="container">
                    <div class="row">
                        <?php echo $breadcrumbs; ?>
                    </div>
                </div>
            </div>
        <?php } ?>
        <div class="container">
            <div class="pi-main-container">
                <!-- Flash messenger -->
                <?php include $this->template('flash-messenger'); ?>
                <div class="row">
                    <!-- Left zone -->
                    <?php if (!empty($blocks['1'])) { ?>
                        <div class="pi-zone-1 col-md-4">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <div class="<?php
                    if (isset($blocks['1']) && isset($blocks['8'])) {
                        echo 'col-md-4';
                    } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                        echo 'col-md-8';
                    } else {
                        echo 'col-md-12';
                    }
                    ?>">
                        <!-- Center top zone -->
                        <?php if (isset($blocks['2'])) { ?>
                            <div class="pi-zone-2">
                                <?php foreach ($blocks['2'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-3">
                                    <?php
                                    if (isset($blocks['3'])) {
                                        foreach ($blocks['3'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-4">
                                    <?php
                                    if (isset($blocks['4'])) {
                                        foreach ($blocks['4'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Module content starts -->
                        <?php if (!empty($content)) { ?>
                            <div class="<?php echo $module; ?>">
                                <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                    <?php echo $content; ?>
                                </div>
                                <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                            </div>
                        <?php } ?>
                        <!-- Module content ends -->
                        <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-5">
                                    <?php
                                    if (isset($blocks['5'])) {
                                        foreach ($blocks['5'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-6">
                                    <?php
                                    if (isset($blocks['6'])) {
                                        foreach ($blocks['6'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Center bottom zone -->
                        <?php if (isset($blocks['7'])) { ?>
                            <div class="pi-zone-7">
                                <?php foreach ($blocks['7'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Right zone -->
                    <?php if (isset($blocks['8'])) { ?>
                        <div class="col-md-4 pi-zone-8">
                            <?php foreach ($blocks['8'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Bottom foot zone -->
                <?php if (isset($blocks['99'])) { ?>
                    <div class="pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>
<!-- Footer: sitelink -->
<footer class="pi-footer">
    <div class="pi-footer-social">
        <div class="container">
            <div class="row">
                <div class="col-md-6 pi-footer-social-text">فضا، فضایی برای ساخت آینده ... </div>
                <div class="col-md-6 text-right">
                    <ul class="list-inline">
                        <li><a href="#" title=""><i class="fa fa-telegram"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-youtube"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-body">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h3><a href="<?php echo Pi::url($this->url('home')); ?>/page/consult" title="مشاوره">مشاوره</a></h3>
                    <ul class="list-unstyled">
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/news/books" title=" کتاب ها"> کتاب ها</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/news/packages" title="بسته های راهنما">بسته های راهنما</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/page/consult" title="طرح ها">طرح ها</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h3><a href="<?php echo Pi::url($this->url('home')); ?>/page/education" title="آموزش">آموزش</a></h3>
                    <ul class="list-unstyled">
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/event/workshop" title="کارگاه های آموزشی">کارگاه های آموزشی</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/event/short-time" title="دوره های کوتاه مدت">دوره های کوتاه مدت</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/news/promotional" title="محتوی آموزشی">محتوی آموزشی</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h3><a href="<?php echo Pi::url($this->url('home')); ?>/shop" title="تامین تجهیزات"> تامین تجهیزات</a></h3>
                    <ul class="list-unstyled">
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/shop" title="مخابرات">مخابرات</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/shop" title="الکترونیک">الکترونیک</a></li>
                        <li><a href="<?php echo Pi::url($this->url('home')); ?>/shop" title="تعیین و کنترل وضعیت">تعیین و کنترل وضعیت</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12" data-rel="license">تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="<?php echo Pi::url($this->url('home')); ?>/"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>